
spring:
  kafka:
    properties:
      bootstrap.servers: localhost:9092
      sasl:
        mechanism: PLAIN
    producer:
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.LongDeserializer
    streams:
      replication-factor:  1
      application-id: spring-boot-streams

